### ISSUE TITLE
[WinError 5] Access is denied

### ISSUE THREAD

**Issue by Festive4020** [slyautomation/osrs_basic_botting_functions#9]
```python
Traceback (most recent call last):
  File "G:\Games\OSRSHelp\osrs_basic_functions-main\cooking.py", line 518, in <module>
    barb_village_powercook_and_fish(Run_Duration_hours=6, invent_full=24)
  File "G:\Games\OSRSHelp\osrs_basic_functions-main\cooking.py", line 451, in barb_village_powercook_and_fish
    fishing_text = Image_to_Text('thresh', 'textshot.png')
  File "G:\Games\OSRSHelp\osrs_basic_functions-main\functions.py", line 203, in Image_to_Text
    text = pytesseract.image_to_string(im, config=parse_config)
  File "G:\Games\OSRSHelp\osrs_basic_functions-main\venv\lib\site-packages\pytesseract\pytesseract.py", line 423, in image_to_string
    return {
  File "G:\Games\OSRSHelp\osrs_basic_functions-main\venv\lib\site-packages\pytesseract\pytesseract.py", line 426, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "G:\Games\OSRSHelp\osrs_basic_functions-main\venv\lib\site-packages\pytesseract\pytesseract.py", line 288, in run_and_get_output
    run_tesseract(**kwargs)
  File "G:\Games\OSRSHelp\osrs_basic_functions-main\venv\lib\site-packages\pytesseract\pytesseract.py", line 255, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

Process finished with exit code 1
```

All scripts end in this issue. It's probably my fault, but is there any more information you need to solve this?

**Comment by Festive4020** [comment]
It was my fault.
